/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CijferRouteImport } from './routes/cijfer'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as MatrijsRouteImport } from './routes/matrijs'
import { Route as MatrijsmakerRouteImport } from './routes/matrijsmaker'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as ToetsIdRouteImport } from './routes/toets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CijferRoute = CijferRouteImport.update({
  id: '/cijfer',
  path: '/cijfer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrijsRoute = MatrijsRouteImport.update({
  id: '/matrijs',
  path: '/matrijs',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrijsmakerRoute = MatrijsmakerRouteImport.update({
  id: '/matrijsmaker',
  path: '/matrijsmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const ToetsIdRoute = ToetsIdRouteImport.update({
  id: '/toets/$id',
  path: '/toets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cijfer': typeof CijferRoute
  '/feedback': typeof FeedbackRoute
  '/matrijs': typeof MatrijsRoute
  '/matrijsmaker': typeof MatrijsmakerRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/toets/$id': typeof ToetsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cijfer': typeof CijferRoute
  '/feedback': typeof FeedbackRoute
  '/matrijs': typeof MatrijsRoute
  '/matrijsmaker': typeof MatrijsmakerRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/toets/$id': typeof ToetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cijfer': typeof CijferRoute
  '/feedback': typeof FeedbackRoute
  '/matrijs': typeof MatrijsRoute
  '/matrijsmaker': typeof MatrijsmakerRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/toets/$id': typeof ToetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cijfer'
    | '/feedback'
    | '/matrijs'
    | '/matrijsmaker'
    | '/werkwijze'
    | '/toets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cijfer'
    | '/feedback'
    | '/matrijs'
    | '/matrijsmaker'
    | '/werkwijze'
    | '/toets/$id'
  id:
    | '__root__'
    | '/'
    | '/cijfer'
    | '/feedback'
    | '/matrijs'
    | '/matrijsmaker'
    | '/werkwijze'
    | '/toets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CijferRoute: typeof CijferRoute
  FeedbackRoute: typeof FeedbackRoute
  MatrijsRoute: typeof MatrijsRoute
  MatrijsmakerRoute: typeof MatrijsmakerRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
  ToetsIdRoute: typeof ToetsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cijfer': {
      id: '/cijfer'
      path: '/cijfer'
      fullPath: '/cijfer'
      preLoaderRoute: typeof CijferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrijs': {
      id: '/matrijs'
      path: '/matrijs'
      fullPath: '/matrijs'
      preLoaderRoute: typeof MatrijsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrijsmaker': {
      id: '/matrijsmaker'
      path: '/matrijsmaker'
      fullPath: '/matrijsmaker'
      preLoaderRoute: typeof MatrijsmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toets/$id': {
      id: '/toets/$id'
      path: '/toets/$id'
      fullPath: '/toets/$id'
      preLoaderRoute: typeof ToetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CijferRoute: CijferRoute,
  FeedbackRoute: FeedbackRoute,
  MatrijsRoute: MatrijsRoute,
  MatrijsmakerRoute: MatrijsmakerRoute,
  WerkwijzeRoute: WerkwijzeRoute,
  ToetsIdRoute: ToetsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
